useGroupedVersion: true

version_info_list:
  - value: latest version(2.4.10)
  - value: 2.x
    child:
      - 2.2.0_cplusplus
      - 2.0.20_cplusplus
      - 2.0.10_cplusplus
      - 2.0.0_cplusplus
  - value: 1.x
    child:
      - 1.0.20_cplusplus
      - 1.0.10_cplusplus
      - 1.0.0_cplusplus
      - 1.0.20_c
      - 1.0.10_c
      - 1.0.0_c

  