useGroupedVersion: true

version_info_list:
  - value: latest version(2.2.10)
  - value: 2.x
    child:
      - 2.2.0
      - 2.0.20
      - 2.0.10
      - 2.0.0
  - value: 1.x
    child:
      - 1.0.20
      - 1.0.10
      - 1.0.0

  